apiVersion: v1
kind: ConfigMap
metadata:
  name: task-web-ui-configmap
data:
    app.config.json: |
      {
          "defaultApiUrl": "http://localhost:3000/api",
          "daprApiUrl": "",
          "daprAppId": ""
      }